export const accOptions = [
    { label: 'Brake', value: 'Brake' },
    { label: 'Fuel', value: 'Fuel' },
    { label: 'Gear', value: 'Gear' },
    { label: 'RPMs', value: 'RPMs' },
    { label: 'SteerAngle', value: 'SteerAngle' },
    { label: 'SpeedKmh', value: 'SpeedKmh' },
    { label: 'TC', value: 'TC' },
    { label: 'Heading', value: 'Heading' },
    { label: 'Pitch', value: 'Pitch' },
    { label: 'Roll', value: 'Roll' },
    { label: 'PitLimiterOn', value: 'PitLimiterOn' },
    { label: 'ABS', value: 'ABS' },
    { label: 'AutoShifterOn', value: 'AutoShifterOn' },
    { label: 'TurboBoost', value: 'TurboBoost' },
    { label: 'AirTemp', value: 'AirTemp' },
    { label: 'RoadTemp', value: 'RoadTemp' },
    { label: 'FinalFF', value: 'FinalFF' },
    { label: 'Clutch', value: 'Clutch' },
    { label: 'IsAIControlled', value: 'IsAIControlled' },
    { label: 'BrakeBias', value: 'BrakeBias' },
    { label: 'WheelSlipFL', value: 'WheelSlipFL' },
    { label: 'WheelSlipFR', value: 'WheelSlipFR' },
    { label: 'WheelSlipRL', value: 'WheelSlipRL' },
    { label: 'WheelSlipRR', value: 'WheelSlipRR' },
    { label: 'WheelsPressureFL', value: 'WheelsPressureFL' },
    { label: 'WheelsPressureFR', value: 'WheelsPressureFR' },
    { label: 'WheelsPressureRL', value: 'WheelsPressureRL' },
    { label: 'WheelsPressureRR', value: 'WheelsPressureRR' },
    { label: 'WheelAngularSpeedFL', value: 'WheelAngularSpeedFL' },
    { label: 'WheelAngularSpeedFR', value: 'WheelAngularSpeedFR' },
    { label: 'WheelAngularSpeedRL', value: 'WheelAngularSpeedRL' },
    { label: 'WheelAngularSpeedRR', value: 'WheelAngularSpeedRR' },
    { label: 'TyreCoreTemperatureFL', value: 'TyreCoreTemperatureFL' },
    { label: 'TyreCoreTemperatureFR', value: 'TyreCoreTemperatureFR' },
    { label: 'TyreCoreTemperatureRL', value: 'TyreCoreTemperatureRL' },
    { label: 'TyreCoreTemperatureRR', value: 'TyreCoreTemperatureRR' },
    { label: 'SuspensionTravelFL', value: 'SuspensionTravelFL' },
    { label: 'SuspensionTravelFR', value: 'SuspensionTravelFR' },
    { label: 'SuspensionTravelRL', value: 'SuspensionTravelRL' },
    { label: 'SuspensionTravelRR', value: 'SuspensionTravelRR' },
    { label: 'SlipRatioFL', value: 'SlipRatioFL' },
    { label: 'SlipRatioFR', value: 'SlipRatioFR' },
    { label: 'SlipRatioRL', value: 'SlipRatioRL' },
    { label: 'SlipRatioRR', value: 'SlipRatioRR' },
    { label: 'SlipAngleFL', value: 'SlipAngleFL' },
    { label: 'SlipAngleFR', value: 'SlipAngleFR' },
    { label: 'SlipAngleRL', value: 'SlipAngleRL' },
    { label: 'SlipAngleRR', value: 'SlipAngleRR' },
    { label: 'BrakeTempFL', value: 'BrakeTempFL' },
    { label: 'BrakeTempFR', value: 'BrakeTempFR' },
    { label: 'BrakeTempRL', value: 'BrakeTempRL' },
    { label: 'BrakeTempRR', value: 'BrakeTempRR' },
    { label: 'VelocityX', value: 'VelocityX' },
    { label: 'VelocityY', value: 'VelocityY' },
    { label: 'VelocityZ', value: 'VelocityZ' },
    { label: 'AccGX', value: 'AccGX' },
    { label: 'AccGY', value: 'AccGY' },
    { label: 'AccGZ', value: 'AccGZ' },
    { label: 'LocalAngularVelX', value: 'LocalAngularVelX' },
    { label: 'LocalAngularVelY', value: 'LocalAngularVelY' },
    { label: 'LocalAngularVelZ', value: 'LocalAngularVelZ' },
    { label: 'LocalVelocityX', value: 'LocalVelocityX' },
    { label: 'LocalVelocityY', value: 'LocalVelocityY' },
    { label: 'LocalVelocityZ', value: 'LocalVelocityZ' },

    // { label: 'TyreContactPointFLX', value: 'TyreContactPointFLX' },
    // { label: 'TyreContactPointFLY', value: 'TyreContactPointFLY' },
    // { label: 'TyreContactPointFLZ', value: 'TyreContactPointFLZ' },
    // { label: 'TyreContactPointFRX', value: 'TyreContactPointFRX' },
    // { label: 'TyreContactPointFRY', value: 'TyreContactPointFRY' },
    // { label: 'TyreContactPointFRZ', value: 'TyreContactPointFRZ' },
    // { label: 'TyreContactPointRLX', value: 'TyreContactPointRLX' },
    // { label: 'TyreContactPointRLY', value: 'TyreContactPointRLY' },
    // { label: 'TyreContactPointRLZ', value: 'TyreContactPointRLZ' },
    // { label: 'TyreContactPointRRX', value: 'TyreContactPointRRX' },
    // { label: 'TyreContactPointRRY', value: 'TyreContactPointRRY' },
    // { label: 'TyreContactPointRRZ', value: 'TyreContactPointRRZ' },
    // { label: 'TyreContactNormalFLX', value: 'TyreContactNormalFLX' },
    // { label: 'TyreContactNormalFLY', value: 'TyreContactNormalFLY' },
    // { label: 'TyreContactNormalFLZ', value: 'TyreContactNormalFLZ' },
    // { label: 'TyreContactNormalFRX', value: 'TyreContactNormalFRX' },
    // { label: 'TyreContactNormalFRY', value: 'TyreContactNormalFRY' },
    // { label: 'TyreContactNormalFRZ', value: 'TyreContactNormalFRZ' },
    // { label: 'TyreContactNormalRLX', value: 'TyreContactNormalRLX' },
    // { label: 'TyreContactNormalRLY', value: 'TyreContactNormalRLY' },
    // { label: 'TyreContactNormalRLZ', value: 'TyreContactNormalRLZ' },
    // { label: 'TyreContactNormalRRX', value: 'TyreContactNormalRRX' },
    // { label: 'TyreContactNormalRRY', value: 'TyreContactNormalRRY' },
    // { label: 'TyreContactNormalRRZ', value: 'TyreContactNormalRRZ' },
    // { label: 'TyreContactHeadingFLX', value: 'TyreContactHeadingFLX' },
    // { label: 'TyreContactHeadingFLY', value: 'TyreContactHeadingFLY' },
    // { label: 'TyreContactHeadingFLZ', value: 'TyreContactHeadingFLZ' },
    // { label: 'TyreContactHeadingFRX', value: 'TyreContactHeadingFRX' },
    // { label: 'TyreContactHeadingFRY', value: 'TyreContactHeadingFRY' },
    // { label: 'TyreContactHeadingFRZ', value: 'TyreContactHeadingFRZ' },
    // { label: 'TyreContactHeadingRLX', value: 'TyreContactHeadingRLX' },
    // { label: 'TyreContactHeadingRLY', value: 'TyreContactHeadingRLY' },
    // { label: 'TyreContactHeadingRLZ', value: 'TyreContactHeadingRLZ' },
    // { label: 'TyreContactHeadingRRX', value: 'TyreContactHeadingRRX' },
    // { label: 'TyreContactHeadingRRY', value: 'TyreContactHeadingRRY' },
    // { label: 'TyreContactHeadingRRZ', value: 'TyreContactHeadingRRZ' },
];
