export const accOptions = [
    { label: 'Brake', value: 'Brake' },
    { label: 'Fuel', value: 'Fuel' },
    { label: 'Gear', value: 'Gear' },
    { label: 'RPMs', value: 'RPMs' },
    { label: 'SteerAngle', value: 'SteerAngle' },
    { label: 'SpeedKmh', value: 'SpeedKmh' },
    { label: 'TC', value: 'TC' },
    { label: 'Heading', value: 'Heading' },
    { label: 'Pitch', value: 'Pitch' },
    { label: 'Roll', value: 'Roll' },
    { label: 'PitLimiterOn', value: 'PitLimiterOn' },
    { label: 'ABS', value: 'ABS' },
    { label: 'AutoShifterOn', value: 'AutoShifterOn' },
    { label: 'TurboBoost', value: 'TurboBoost' },
    { label: 'AirTemp', value: 'AirTemp' },
    { label: 'RoadTemp', value: 'RoadTemp' },
    { label: 'FinalFF', value: 'FinalFF' },
    { label: 'Clutch', value: 'Clutch' },
    { label: 'IsAIControlled', value: 'IsAIControlled' },
    { label: 'BrakeBias', value: 'BrakeBias' },
    { label: 'WheelSlipFL', value: 'WheelSlipFL' },
    { label: 'WheelSlipFR', value: 'WheelSlipFR' },
    { label: 'WheelSlipRL', value: 'WheelSlipRL' },
    { label: 'WheelSlipRR', value: 'WheelSlipRR' },
    { label: 'WheelsPressureFL', value: 'WheelsPressureFL' },
    { label: 'WheelsPressureFR', value: 'WheelsPressureFR' },
    { label: 'WheelsPressureRL', value: 'WheelsPressureRL' },
    { label: 'WheelsPressureRR', value: 'WheelsPressureRR' },
    { label: 'WheelAngularSpeedFL', value: 'WheelAngularSpeedFL' },
    { label: 'WheelAngularSpeedFR', value: 'WheelAngularSpeedFR' },
    { label: 'WheelAngularSpeedRL', value: 'WheelAngularSpeedRL' },
    { label: 'WheelAngularSpeedRR', value: 'WheelAngularSpeedRR' },
    { label: 'TyreCoreTemperatureFL', value: 'TyreCoreTemperatureFL' },
    { label: 'TyreCoreTemperatureFR', value: 'TyreCoreTemperatureFR' },
    { label: 'TyreCoreTemperatureRL', value: 'TyreCoreTemperatureRL' },
    { label: 'TyreCoreTemperatureRR', value: 'TyreCoreTemperatureRR' },
    { label: 'SuspensionTravelFL', value: 'SuspensionTravelFL' },
    { label: 'SuspensionTravelFR', value: 'SuspensionTravelFR' },
    { label: 'SuspensionTravelRL', value: 'SuspensionTravelRL' },
    { label: 'SuspensionTravelRR', value: 'SuspensionTravelRR' },
    { label: 'SlipRatioFL', value: 'SlipRatioFL' },
    { label: 'SlipRatioFR', value: 'SlipRatioFR' },
    { label: 'SlipRatioRL', value: 'SlipRatioRL' },
    { label: 'SlipRatioRR', value: 'SlipRatioRR' },
    { label: 'SlipAngleFL', value: 'SlipAngleFL' },
    { label: 'SlipAngleFR', value: 'SlipAngleFR' },
    { label: 'SlipAngleRL', value: 'SlipAngleRL' },
    { label: 'SlipAngleRR', value: 'SlipAngleRR' },
    { label: 'BrakeTempFL', value: 'BrakeTempFL' },
    { label: 'BrakeTempFR', value: 'BrakeTempFR' },
    { label: 'BrakeTempRL', value: 'BrakeTempRL' },
    { label: 'BrakeTempRR', value: 'BrakeTempRR' },
    { label: 'VelocityX', value: 'VelocityX' },
    { label: 'VelocityY', value: 'VelocityY' },
    { label: 'VelocityZ', value: 'VelocityZ' },
    { label: 'AccGX', value: 'AccGX' },
    { label: 'AccGY', value: 'AccGY' },
    { label: 'AccGZ', value: 'AccGZ' },
    { label: 'LocalAngularVelX', value: 'LocalAngularVelX' },
    { label: 'LocalAngularVelY', value: 'LocalAngularVelY' },
    { label: 'LocalAngularVelZ', value: 'LocalAngularVelZ' },
    { label: 'LocalVelocityX', value: 'LocalVelocityX' },
    { label: 'LocalVelocityY', value: 'LocalVelocityY' },
    { label: 'LocalVelocityZ', value: 'LocalVelocityZ' },

    // { label: 'TyreContactPointFLX', value: 'TyreContactPointFLX' },
    // { label: 'TyreContactPointFLY', value: 'TyreContactPointFLY' },
    // { label: 'TyreContactPointFLZ', value: 'TyreContactPointFLZ' },
    // { label: 'TyreContactPointFRX', value: 'TyreContactPointFRX' },
    // { label: 'TyreContactPointFRY', value: 'TyreContactPointFRY' },
    // { label: 'TyreContactPointFRZ', value: 'TyreContactPointFRZ' },
    // { label: 'TyreContactPointRLX', value: 'TyreContactPointRLX' },
    // { label: 'TyreContactPointRLY', value: 'TyreContactPointRLY' },
    // { label: 'TyreContactPointRLZ', value: 'TyreContactPointRLZ' },
    // { label: 'TyreContactPointRRX', value: 'TyreContactPointRRX' },
    // { label: 'TyreContactPointRRY', value: 'TyreContactPointRRY' },
    // { label: 'TyreContactPointRRZ', value: 'TyreContactPointRRZ' },
    // { label: 'TyreContactNormalFLX', value: 'TyreContactNormalFLX' },
    // { label: 'TyreContactNormalFLY', value: 'TyreContactNormalFLY' },
    // { label: 'TyreContactNormalFLZ', value: 'TyreContactNormalFLZ' },
    // { label: 'TyreContactNormalFRX', value: 'TyreContactNormalFRX' },
    // { label: 'TyreContactNormalFRY', value: 'TyreContactNormalFRY' },
    // { label: 'TyreContactNormalFRZ', value: 'TyreContactNormalFRZ' },
    // { label: 'TyreContactNormalRLX', value: 'TyreContactNormalRLX' },
    // { label: 'TyreContactNormalRLY', value: 'TyreContactNormalRLY' },
    // { label: 'TyreContactNormalRLZ', value: 'TyreContactNormalRLZ' },
    // { label: 'TyreContactNormalRRX', value: 'TyreContactNormalRRX' },
    // { label: 'TyreContactNormalRRY', value: 'TyreContactNormalRRY' },
    // { label: 'TyreContactNormalRRZ', value: 'TyreContactNormalRRZ' },
    // { label: 'TyreContactHeadingFLX', value: 'TyreContactHeadingFLX' },
    // { label: 'TyreContactHeadingFLY', value: 'TyreContactHeadingFLY' },
    // { label: 'TyreContactHeadingFLZ', value: 'TyreContactHeadingFLZ' },
    // { label: 'TyreContactHeadingFRX', value: 'TyreContactHeadingFRX' },
    // { label: 'TyreContactHeadingFRY', value: 'TyreContactHeadingFRY' },
    // { label: 'TyreContactHeadingFRZ', value: 'TyreContactHeadingFRZ' },
    // { label: 'TyreContactHeadingRLX', value: 'TyreContactHeadingRLX' },
    // { label: 'TyreContactHeadingRLY', value: 'TyreContactHeadingRLY' },
    // { label: 'TyreContactHeadingRLZ', value: 'TyreContactHeadingRLZ' },
    // { label: 'TyreContactHeadingRRX', value: 'TyreContactHeadingRRX' },
    // { label: 'TyreContactHeadingRRY', value: 'TyreContactHeadingRRY' },
    // { label: 'TyreContactHeadingRRZ', value: 'TyreContactHeadingRRZ' },

    { label: 'Status', value: 'Status' },
    { label: 'Session', value: 'Session' },
    { label: 'CurrentTime', value: 'CurrentTime' },
    { label: 'LastTime', value: 'LastTime' },
    { label: 'BestTime', value: 'BestTime' },
    { label: 'Split', value: 'Split' },
    { label: 'CompletedLaps', value: 'CompletedLaps' },
    { label: 'Position', value: 'Position' },
    { label: 'ICurrentTime', value: 'ICurrentTime' },
    { label: 'ILastTime', value: 'ILastTime' },
    { label: 'IBestTime', value: 'IBestTime' },
    { label: 'SessionTimeLeft', value: 'SessionTimeLeft' },
    { label: 'DistanceTraveled', value: 'DistanceTraveled' },
    { label: 'IsInPit', value: 'IsInPit' },
    { label: 'CurrentSectorIndex', value: 'CurrentSectorIndex' },
    { label: 'LastSectorTime', value: 'LastSectorTime' },
    { label: 'NumberOfLaps', value: 'NumberOfLaps' },
    { label: 'TyreCompound', value: 'TyreCompound' },
    { label: 'ReplayTimeMultiplier', value: 'ReplayTimeMultiplier' },
    { label: 'NormalizedCarPosition', value: 'NormalizedCarPosition' },
    { label: 'ActiveCars', value: 'ActiveCars' },
    { label: 'CarCoordinates', value: 'CarCoordinates' },
    { label: 'CarId', value: 'CarId' },
    { label: 'PlayercarId', value: 'PlayercarId' },
    { label: 'PenaltyTime', value: 'PenaltyTime' },
    { label: 'Flag', value: 'Flag' },
    { label: 'Penalty', value: 'Penalty' },
    { label: 'IdealLineOn', value: 'IdealLineOn' },
    { label: 'IsInPitLane', value: 'IsInPitLane' },
    { label: 'SurfaceGrip', value: 'SurfaceGrip' },
    { label: 'MandatoryPitDone', value: 'MandatoryPitDone' },
    { label: 'WindSpeed', value: 'WindSpeed' },
    { label: 'WindDirection', value: 'WindDirection' },
    { label: 'IsSetupMenuVisible', value: 'IsSetupMenuVisible' },
    { label: 'MainDisplayIndex', value: 'MainDisplayIndex' },
    { label: 'SecondaryDisplayIndex', value: 'SecondaryDisplayIndex' },
    { label: 'TCLevel', value: 'TCLevel' },
    { label: 'TCCut', value: 'TCCut' },
    { label: 'EngineMap', value: 'EngineMap' },
    { label: 'ABSLevel', value: 'ABSLevel' },
    { label: 'FuelxLap', value: 'FuelxLap' },
    { label: 'RainLights', value: 'RainLights' },
    { label: 'FlashingLights', value: 'FlashingLights' },
    { label: 'LightsStage', value: 'LightsStage' },
    { label: 'ExhaustTemperature', value: 'ExhaustTemperature' },
    { label: 'WiperLv', value: 'WiperLv' },
    { label: 'DriverStintTotalTimeLeft', value: 'DriverStintTotalTimeLeft' },
    { label: 'DriverStintTimeLeft', value: 'DriverStintTimeLeft' },
    { label: 'RainTyres', value: 'RainTyres' },
    { label: 'SessionIndex', value: 'SessionIndex' },
    { label: 'UsedFuel', value: 'UsedFuel' },
    { label: 'DeltaLapTime', value: 'DeltaLapTime' },
    { label: 'IDeltaLapTime', value: 'IDeltaLapTime' },
    { label: 'EstimatedLapTime', value: 'EstimatedLapTime' },
    { label: 'IEstimatedLapTime', value: 'IEstimatedLapTime' },
    { label: 'IsDeltaPositive', value: 'IsDeltaPositive' },
    { label: 'ISplit', value: 'ISplit' },
    { label: 'IsValidLap', value: 'IsValidLap' },
    { label: 'FuelEstimatedLaps', value: 'FuelEstimatedLaps' },
    { label: 'TrackStatus', value: 'TrackStatus' },
    { label: 'MissingMandatoryPits', value: 'MissingMandatoryPits' },
    { label: 'Clock', value: 'Clock' },
    { label: 'DirectionLightsLeft', value: 'DirectionLightsLeft' },
    { label: 'DirectionLightsRight', value: 'DirectionLightsRight' },
    { label: 'MfdTyreSet', value: 'MfdTyreSet' },
    { label: 'TrackGripStatus', value: 'TrackGripStatus' },
    { label: 'RainIntensity', value: 'RainIntensity' },
    { label: 'RainIntensityIn10min', value: 'RainIntensityIn10min' },
    { label: 'RainIntensityIn30min', value: 'RainIntensityIn30min' },

    { label: 'All', value: '*' },
];
