export const iRacingOptions = [
    { label: 'SessionTime', value: 'SessionTime'},
    { label: 'SessionTick', value: 'SessionTick'},
    { label: 'SessionNum', value: 'SessionNum'},
    { label: 'SessionState', value: 'SessionState'},
    { label: 'SessionUniqueID', value: 'SessionUniqueID'},
    { label: 'SessionFlags', value: 'SessionFlags'},
    { label: 'SessionTimeRemain', value: 'SessionTimeRemain'},
    { label: 'SessionLapsRemain', value: 'SessionLapsRemain'},
    { label: 'SessionLapsRemainEx', value: 'SessionLapsRemainEx'},
    { label: 'SessionTimeTotal', value: 'SessionTimeTotal'},
    { label: 'SessionLapsTotal', value: 'SessionLapsTotal'},
    { label: 'SessionTimeOfDay', value: 'SessionTimeOfDay'},
    { label: 'RadioTransmitCarIdx', value: 'RadioTransmitCarIdx'},
    { label: 'RadioTransmitRadioIdx', value: 'RadioTransmitRadioIdx'},
    { label: 'RadioTransmitFrequencyIdx', value: 'RadioTransmitFrequencyIdx'},
    { label: 'DisplayUnits', value: 'DisplayUnits'},
    { label: 'DriverMarker', value: 'DriverMarker'},
    { label: 'PushToPass', value: 'PushToPass'},
    { label: 'ManualBoost', value: 'ManualBoost'},
    { label: 'ManualNoBoost', value: 'ManualNoBoost'},
    { label: 'IsOnTrack', value: 'IsOnTrack'},
    { label: 'IsReplayPlaying', value: 'IsReplayPlaying'},
    { label: 'ReplayFrameNum', value: 'ReplayFrameNum'},
    { label: 'ReplayFrameNumEnd', value: 'ReplayFrameNumEnd'},
    { label: 'IsDiskLoggingEnabled', value: 'IsDiskLoggingEnabled'},
    { label: 'IsDiskLoggingActive', value: 'IsDiskLoggingActive'},
    { label: 'FrameRate', value: 'FrameRate'},
    { label: 'CpuUsageFG', value: 'CpuUsageFG'},
    { label: 'GpuUsage', value: 'GpuUsage'},
    { label: 'ChanAvgLatency', value: 'ChanAvgLatency'},
    { label: 'ChanLatency', value: 'ChanLatency'},
    { label: 'ChanQuality', value: 'ChanQuality'},
    { label: 'ChanPartnerQuality', value: 'ChanPartnerQuality'},
    { label: 'CpuUsageBG', value: 'CpuUsageBG'},
    { label: 'ChanClockSkew', value: 'ChanClockSkew'},
    { label: 'MemPageFaultSec', value: 'MemPageFaultSec'},
    { label: 'PlayerCarPosition', value: 'PlayerCarPosition'},
    { label: 'PlayerCarClassPosition', value: 'PlayerCarClassPosition'},
    { label: 'PlayerCarClass', value: 'PlayerCarClass'},
    { label: 'PlayerTrackSurface', value: 'PlayerTrackSurface'},
    { label: 'PlayerTrackSurfaceMaterial', value: 'PlayerTrackSurfaceMaterial'},
    { label: 'PlayerCarIdx', value: 'PlayerCarIdx'},
    { label: 'PlayerCarTeamIncidentCount', value: 'PlayerCarTeamIncidentCount'},
    { label: 'PlayerCarMyIncidentCount', value: 'PlayerCarMyIncidentCount'},
    { label: 'PlayerCarDriverIncidentCount', value: 'PlayerCarDriverIncidentCount'},
    { label: 'PlayerCarWeightPenalty', value: 'PlayerCarWeightPenalty'},
    { label: 'PlayerCarPowerAdjust', value: 'PlayerCarPowerAdjust'},
    { label: 'PlayerCarDryTireSetLimit', value: 'PlayerCarDryTireSetLimit'},
    { label: 'PlayerCarTowTime', value: 'PlayerCarTowTime'},
    { label: 'PlayerCarInPitStall', value: 'PlayerCarInPitStall'},
    { label: 'PlayerCarPitSvStatus', value: 'PlayerCarPitSvStatus'},
    { label: 'PlayerTireCompound', value: 'PlayerTireCompound'},
    { label: 'PlayerFastRepairsUsed', value: 'PlayerFastRepairsUsed'},
    // { label: 'CarIdxLap', value: 'CarIdxLap'},
    // { label: 'CarIdxLapCompleted', value: 'CarIdxLapCompleted'},
    // { label: 'CarIdxLapDistPct', value: 'CarIdxLapDistPct'},
    // { label: 'CarIdxTrackSurface', value: 'CarIdxTrackSurface'},
    // { label: 'CarIdxTrackSurfaceMaterial', value: 'CarIdxTrackSurfaceMaterial'},
    // { label: 'CarIdxOnPitRoad', value: 'CarIdxOnPitRoad'},
    // { label: 'CarIdxPosition', value: 'CarIdxPosition'},
    // { label: 'CarIdxClassPosition', value: 'CarIdxClassPosition'},
    // { label: 'CarIdxClass', value: 'CarIdxClass'},
    // { label: 'CarIdxF2Time', value: 'CarIdxF2Time'},
    // { label: 'CarIdxEstTime', value: 'CarIdxEstTime'},
    // { label: 'CarIdxLastLapTime', value: 'CarIdxLastLapTime'},
    // { label: 'CarIdxBestLapTime', value: 'CarIdxBestLapTime'},
    // { label: 'CarIdxBestLapNum', value: 'CarIdxBestLapNum'},
    // { label: 'CarIdxTireCompound', value: 'CarIdxTireCompound'},
    // { label: 'CarIdxQualTireCompound', value: 'CarIdxQualTireCompound'},
    // { label: 'CarIdxQualTireCompoundLocked', value: 'CarIdxQualTireCompoundLocked'},
    // { label: 'CarIdxFastRepairsUsed', value: 'CarIdxFastRepairsUsed'},
    // { label: 'CarIdxPaceLine', value: 'CarIdxPaceLine'},
    // { label: 'CarIdxPaceRow', value: 'CarIdxPaceRow'},
    // { label: 'CarIdxPaceFlags', value: 'CarIdxPaceFlags'},
    // { label: 'CarIdxSteer', value: 'CarIdxSteer'},
    // { label: 'CarIdxRPM', value: 'CarIdxRPM'},
    // { label: 'CarIdxGear', value: 'CarIdxGear'},
    // { label: 'CamCarIdx', value: 'CamCarIdx'},
    // { label: 'CarIdxP2P_Status', value: 'CarIdxP2P_Status'},
    // { label: 'CarIdxP2P_Count', value: 'CarIdxP2P_Count'},
    { label: 'PaceMode', value: 'PaceMode'},
    { label: 'OnPitRoad', value: 'OnPitRoad'},
    { label: 'SteeringWheelAngle', value: 'SteeringWheelAngle'},
    { label: 'Throttle', value: 'Throttle'},
    { label: 'Brake', value: 'Brake'},
    { label: 'Clutch', value: 'Clutch'},
    { label: 'Gear', value: 'Gear'},
    { label: 'RPM', value: 'RPM'},
    { label: 'Lap', value: 'Lap'},
    { label: 'LapCompleted', value: 'LapCompleted'},
    { label: 'LapDist', value: 'LapDist'},
    { label: 'LapDistPct', value: 'LapDistPct'},
    { label: 'RaceLaps', value: 'RaceLaps'},
    { label: 'LapBestLap', value: 'LapBestLap'},
    { label: 'LapBestLapTime', value: 'LapBestLapTime'},
    { label: 'LapLastLapTime', value: 'LapLastLapTime'},
    { label: 'LapCurrentLapTime', value: 'LapCurrentLapTime'},
    { label: 'LapLasNLapSeq', value: 'LapLasNLapSeq'},
    { label: 'LapLastNLapTime', value: 'LapLastNLapTime'},
    { label: 'LapBestNLapLap', value: 'LapBestNLapLap'},
    { label: 'LapBestNLapTime', value: 'LapBestNLapTime'},
    { label: 'LapDeltaToBestLap', value: 'LapDeltaToBestLap'},
    { label: 'LapDeltaToBestLap_DD', value: 'LapDeltaToBestLap_DD'},
    { label: 'LapDeltaToBestLap_OK', value: 'LapDeltaToBestLap_OK'},
    { label: 'LapDeltaToOptimalLap', value: 'LapDeltaToOptimalLap'},
    { label: 'LapDeltaToOptimalLap_DD', value: 'LapDeltaToOptimalLap_DD'},
    { label: 'LapDeltaToOptimalLap_OK', value: 'LapDeltaToOptimalLap_OK'},
    { label: 'LapDeltaToSessionBestLap', value: 'LapDeltaToSessionBestLap'},
    { label: 'LapDeltaToSessionBestLap_DD', value: 'LapDeltaToSessionBestLap_DD'},
    { label: 'LapDeltaToSessionBestLap_OK', value: 'LapDeltaToSessionBestLap_OK'},
    { label: 'LapDeltaToSessionOptimalLap', value: 'LapDeltaToSessionOptimalLap'},
    { label: 'LapDeltaToSessionOptimalLap_DD', value: 'LapDeltaToSessionOptimalLap_DD'},
    { label: 'LapDeltaToSessionOptimalLap_OK', value: 'LapDeltaToSessionOptimalLap_OK'},
    { label: 'LapDeltaToSessionLastlLap', value: 'LapDeltaToSessionLastlLap'},
    { label: 'LapDeltaToSessionLastlLap_DD', value: 'LapDeltaToSessionLastlLap_DD'},
    { label: 'LapDeltaToSessionLastlLap_OK', value: 'LapDeltaToSessionLastlLap_OK'},
    { label: 'Speed', value: 'Speed'},
    { label: 'Yaw', value: 'Yaw'},
    { label: 'YawNorth', value: 'YawNorth'},
    { label: 'Pitch', value: 'Pitch'},
    { label: 'Roll', value: 'Roll'},
    { label: 'EnterExitReset', value: 'EnterExitReset'},
    { label: 'TrackTemp', value: 'TrackTemp'},
    { label: 'TrackTempCrew', value: 'TrackTempCrew'},
    { label: 'AirTemp', value: 'AirTemp'},
    { label: 'WeatherType', value: 'WeatherType'},
    { label: 'Skies', value: 'Skies'},
    { label: 'AirDensity', value: 'AirDensity'},
    { label: 'AirPressure', value: 'AirPressure'},
    { label: 'WindVel', value: 'WindVel'},
    { label: 'WindDir', value: 'WindDir'},
    { label: 'RelativeHumidity', value: 'RelativeHumidity'},
    { label: 'FogLevel', value: 'FogLevel'},
    { label: 'DCLapStatus', value: 'DCLapStatus'},
    { label: 'DCDriversSoFar', value: 'DCDriversSoFar'},
    { label: 'OkToReloadTextures', value: 'OkToReloadTextures'},
    { label: 'LoadNumTextures', value: 'LoadNumTextures'},
    { label: 'CarLeftRight', value: 'CarLeftRight'},
    { label: 'PitsOpen', value: 'PitsOpen'},
    { label: 'VidCapEnabled', value: 'VidCapEnabled'},
    { label: 'VidCapActive', value: 'VidCapActive'},
    { label: 'PitRepairLeft', value: 'PitRepairLeft'},
    { label: 'PitOptRepairLeft', value: 'PitOptRepairLeft'},
    { label: 'PitstopActive', value: 'PitstopActive'},
    { label: 'FastRepairUsed', value: 'FastRepairUsed'},
    { label: 'FastRepairAvailable', value: 'FastRepairAvailable'},
    { label: 'LFTiresUsed', value: 'LFTiresUsed'},
    { label: 'RFTiresUsed', value: 'RFTiresUsed'},
    { label: 'LRTiresUsed', value: 'LRTiresUsed'},
    { label: 'RRTiresUsed', value: 'RRTiresUsed'},
    { label: 'LeftTireSetsUsed', value: 'LeftTireSetsUsed'},
    { label: 'RightTireSetsUsed', value: 'RightTireSetsUsed'},
    { label: 'FrontTireSetsUsed', value: 'FrontTireSetsUsed'},
    { label: 'RearTireSetsUsed', value: 'RearTireSetsUsed'},
    { label: 'TireSetsUsed', value: 'TireSetsUsed'},
    { label: 'LFTiresAvailable', value: 'LFTiresAvailable'},
    { label: 'RFTiresAvailable', value: 'RFTiresAvailable'},
    { label: 'LRTiresAvailable', value: 'LRTiresAvailable'},
    { label: 'RRTiresAvailable', value: 'RRTiresAvailable'},
    { label: 'LeftTireSetsAvailable', value: 'LeftTireSetsAvailable'},
    { label: 'RightTireSetsAvailable', value: 'RightTireSetsAvailable'},
    { label: 'FrontTireSetsAvailable', value: 'FrontTireSetsAvailable'},
    { label: 'RearTireSetsAvailable', value: 'RearTireSetsAvailable'},
    { label: 'TireSetsAvailable', value: 'TireSetsAvailable'},
    { label: 'CamCameraNumber', value: 'CamCameraNumber'},
    { label: 'CamGroupNumber', value: 'CamGroupNumber'},
    { label: 'CamCameraState', value: 'CamCameraState'},
    { label: 'IsOnTrackCar', value: 'IsOnTrackCar'},
    { label: 'IsInGarage', value: 'IsInGarage'},
    { label: 'SteeringWheelPctTorque', value: 'SteeringWheelPctTorque'},
    { label: 'SteeringWheelPctTorqueSign', value: 'SteeringWheelPctTorqueSign'},
    { label: 'SteeringWheelPctTorqueSignStops', value: 'SteeringWheelPctTorqueSignStops'},
    { label: 'SteeringWheelPctDamper', value: 'SteeringWheelPctDamper'},
    { label: 'SteeringWheelAngleMax', value: 'SteeringWheelAngleMax'},
    { label: 'SteeringWheelLimiter', value: 'SteeringWheelLimiter'},
    { label: 'ShiftIndicatorPct', value: 'ShiftIndicatorPct'},
    { label: 'ShiftPowerPct', value: 'ShiftPowerPct'},
    { label: 'ShiftGrindRPM', value: 'ShiftGrindRPM'},
    { label: 'ThrottleRaw', value: 'ThrottleRaw'},
    { label: 'BrakeRaw', value: 'BrakeRaw'},
    { label: 'HandbrakeRaw', value: 'HandbrakeRaw'},
    { label: 'SteeringWheelPeakForceNm', value: 'SteeringWheelPeakForceNm'},
    { label: 'SteeringWheelMaxForceNm', value: 'SteeringWheelMaxForceNm'},
    { label: 'SteeringWheelUseLinear', value: 'SteeringWheelUseLinear'},
    { label: 'BrakeABSactive', value: 'BrakeABSactive'},
    { label: 'EngineWarnings', value: 'EngineWarnings'},
    { label: 'FuelLevel', value: 'FuelLevel'},
    { label: 'FuelLevelPct', value: 'FuelLevelPct'},
    { label: 'PitSvFlags', value: 'PitSvFlags'},
    { label: 'PitSvLFP', value: 'PitSvLFP'},
    { label: 'PitSvRFP', value: 'PitSvRFP'},
    { label: 'PitSvLRP', value: 'PitSvLRP'},
    { label: 'PitSvRRP', value: 'PitSvRRP'},
    { label: 'PitSvFuel', value: 'PitSvFuel'},
    { label: 'PitSvTireCompound', value: 'PitSvTireCompound'},
    { label: 'ReplayPlaySpeed', value: 'ReplayPlaySpeed'},
    { label: 'ReplayPlaySlowMotion', value: 'ReplayPlaySlowMotion'},
    { label: 'ReplaySessionTime', value: 'ReplaySessionTime'},
    { label: 'ReplaySessionNum', value: 'ReplaySessionNum'},
    { label: 'TireLF_RumblePitch', value: 'TireLF_RumblePitch'},
    { label: 'TireRF_RumblePitch', value: 'TireRF_RumblePitch'},
    { label: 'TireLR_RumblePitch', value: 'TireLR_RumblePitch'},
    { label: 'TireRR_RumblePitch', value: 'TireRR_RumblePitch'},
    { label: 'SteeringWheelTorque_ST', value: 'SteeringWheelTorque_ST'},
    { label: 'SteeringWheelTorque', value: 'SteeringWheelTorque'},
    { label: 'VelocityZ_ST', value: 'VelocityZ_ST'},
    { label: 'VelocityY_ST', value: 'VelocityY_ST'},
    { label: 'VelocityX_ST', value: 'VelocityX_ST'},
    { label: 'VelocityZ', value: 'VelocityZ'},
    { label: 'VelocityY', value: 'VelocityY'},
    { label: 'VelocityX', value: 'VelocityX'},
    { label: 'YawRate_ST', value: 'YawRate_ST'},
    { label: 'PitchRate_ST', value: 'PitchRate_ST'},
    { label: 'RollRate_ST', value: 'RollRate_ST'},
    { label: 'YawRate', value: 'YawRate'},
    { label: 'PitchRate', value: 'PitchRate'},
    { label: 'RollRate', value: 'RollRate'},
    { label: 'VertAccel_ST', value: 'VertAccel_ST'},
    { label: 'LatAccel_ST', value: 'LatAccel_ST'},
    { label: 'LongAccel_ST', value: 'LongAccel_ST'},
    { label: 'VertAccel', value: 'VertAccel'},
    { label: 'LatAccel', value: 'LatAccel'},
    { label: 'LongAccel', value: 'LongAccel'},
    { label: 'dcStarter', value: 'dcStarter'},
    { label: 'dcToggleWindshieldWipers', value: 'dcToggleWindshieldWipers'},
    { label: 'dcTriggerWindshieldWipers', value: 'dcTriggerWindshieldWipers'},
    { label: 'dpRFTireChange', value: 'dpRFTireChange'},
    { label: 'dpLFTireChange', value: 'dpLFTireChange'},
    { label: 'dpRRTireChange', value: 'dpRRTireChange'},
    { label: 'dpLRTireChange', value: 'dpLRTireChange'},
    { label: 'dpFuelFill', value: 'dpFuelFill'},
    { label: 'dpWindshieldTearoff', value: 'dpWindshieldTearoff'},
    { label: 'dpFuelAddKg', value: 'dpFuelAddKg'},
    { label: 'dpFastRepair', value: 'dpFastRepair'},
    { label: 'dcBrakeBias', value: 'dcBrakeBias'},
    { label: 'dcLaunchRPM', value: 'dcLaunchRPM'},
    { label: 'dpLFTireColdPress', value: 'dpLFTireColdPress'},
    { label: 'dpRFTireColdPress', value: 'dpRFTireColdPress'},
    { label: 'dpLRTireColdPress', value: 'dpLRTireColdPress'},
    { label: 'dpRRTireColdPress', value: 'dpRRTireColdPress'},
    { label: 'WaterTemp', value: 'WaterTemp'},
    { label: 'WaterLevel', value: 'WaterLevel'},
    { label: 'FuelPress', value: 'FuelPress'},
    { label: 'FuelUsePerHour', value: 'FuelUsePerHour'},
    { label: 'OilTemp', value: 'OilTemp'},
    { label: 'OilPress', value: 'OilPress'},
    { label: 'OilLevel', value: 'OilLevel'},
    { label: 'Voltage', value: 'Voltage'},
    { label: 'ManifoldPress', value: 'ManifoldPress'},
    { label: 'RFbrakeLinePress', value: 'RFbrakeLinePress'},
    { label: 'RFcoldPressure', value: 'RFcoldPressure'},
    { label: 'RFtempCL', value: 'RFtempCL'},
    { label: 'RFtempCM', value: 'RFtempCM'},
    { label: 'RFtempCR', value: 'RFtempCR'},
    { label: 'RFwearL', value: 'RFwearL'},
    { label: 'RFwearM', value: 'RFwearM'},
    { label: 'RFwearR', value: 'RFwearR'},
    { label: 'LFbrakeLinePress', value: 'LFbrakeLinePress'},
    { label: 'LFcoldPressure', value: 'LFcoldPressure'},
    { label: 'LFtempCL', value: 'LFtempCL'},
    { label: 'LFtempCM', value: 'LFtempCM'},
    { label: 'LFtempCR', value: 'LFtempCR'},
    { label: 'LFwearL', value: 'LFwearL'},
    { label: 'LFwearM', value: 'LFwearM'},
    { label: 'LFwearR', value: 'LFwearR'},
    { label: 'RRbrakeLinePress', value: 'RRbrakeLinePress'},
    { label: 'RRcoldPressure', value: 'RRcoldPressure'},
    { label: 'RRtempCL', value: 'RRtempCL'},
    { label: 'RRtempCM', value: 'RRtempCM'},
    { label: 'RRtempCR', value: 'RRtempCR'},
    { label: 'RRwearL', value: 'RRwearL'},
    { label: 'RRwearM', value: 'RRwearM'},
    { label: 'RRwearR', value: 'RRwearR'},
    { label: 'LRbrakeLinePress', value: 'LRbrakeLinePress'},
    { label: 'LRcoldPressure', value: 'LRcoldPressure'},
    { label: 'LRtempCL', value: 'LRtempCL'},
    { label: 'LRtempCM', value: 'LRtempCM'},
    { label: 'LRtempCR', value: 'LRtempCR'},
    { label: 'LRwearL', value: 'LRwearL'},
    { label: 'LRwearM', value: 'LRwearM'},
    { label: 'LRwearR', value: 'LRwearR'},
    { label: 'RRshockDefl', value: 'RRshockDefl'},
    { label: 'RRshockDefl_ST', value: 'RRshockDefl_ST'},
    { label: 'RRshockVel', value: 'RRshockVel'},
    { label: 'RRshockVel_ST', value: 'RRshockVel_ST'},
    { label: 'LRshockDefl', value: 'LRshockDefl'},
    { label: 'LRshockDefl_ST', value: 'LRshockDefl_ST'},
    { label: 'LRshockVel', value: 'LRshockVel'},
    { label: 'LRshockVel_ST', value: 'LRshockVel_ST'},
    { label: 'RFshockDefl', value: 'RFshockDefl'},
    { label: 'RFshockDefl_ST', value: 'RFshockDefl_ST'},
    { label: 'RFshockVel', value: 'RFshockVel'},
    { label: 'RFshockVel_ST', value: 'RFshockVel_ST'},
    { label: 'LFshockDefl', value: 'LFshockDefl'},
    { label: 'LFshockDefl_ST', value: 'LFshockDefl_ST'},
    { label: 'LFshockVel', value: 'LFshockVel'},
    { label: 'LFshockVel_ST', value: 'LFshockVel_ST'},

    // Car-specific values
    { label: 'CFrideHeight', value: 'CFrideHeight' },
    { label: 'CFshockDefl', value: 'CFshockDefl' },
    { label: 'CFshockVel', value: 'CFshockVel' },
    { label: 'CFSRrideHeight', value: 'CFSRrideHeight' },
    { label: 'CRrideHeight', value: 'CRrideHeight' },
    { label: 'CRshockDefl', value: 'CRshockDefl' },
    { label: 'CRshockVel', value: 'CRshockVel' },
    { label: 'dcABS', value: 'dcABS' },
    { label: 'dcAntiRollFront', value: 'dcAntiRollFront' },
    { label: 'dcAntiRollRear', value: 'dcAntiRollRear' },
    { label: 'dcBoostLevel', value: 'dcBoostLevel' },
    { label: 'dcBrakeBias', value: 'dcBrakeBias' },
    { label: 'dcBrakeBias', value: 'dcBrakeBias' },
    { label: 'dcDiffEntry', value: 'dcDiffEntry' },
    { label: 'dcDiffExit', value: 'dcDiffExit' },
    { label: 'dcDiffMiddle', value: 'dcDiffMiddle' },
    { label: 'dcEngineBraking', value: 'dcEngineBraking' },
    { label: 'dcEnginePower', value: 'dcEnginePower' },
    { label: 'dcFuelMixture', value: 'dcFuelMixture' },
    { label: 'dcRevLimiter', value: 'dcRevLimiter' },
    { label: 'dcThrottleShape', value: 'dcThrottleShape' },
    { label: 'dcTractionControl', value: 'dcTractionControl' },
    { label: 'dcTractionControl2', value: 'dcTractionControl2' },
    { label: 'dcTractionControlToggle', value: 'dcTractionControlToggle' },
    { label: 'dcWeightJackerLeft', value: 'dcWeightJackerLeft' },
    { label: 'dcWeightJackerRight', value: 'dcWeightJackerRight' },
    { label: 'dcWingFront', value: 'dcWingFront' },
    { label: 'dcWingRear', value: 'dcWingRear' },
    { label: 'dpFNOMKnobSetting', value: 'dpFNOMKnobSetting' },
    { label: 'dpFUFangleIndex', value: 'dpFUFangleIndex' },
    { label: 'dpFWingAngle', value: 'dpFWingAngle' },
    { label: 'dpFWingIndex', value: 'dpFWingIndex' },
    { label: 'dpLrWedgeAdj', value: 'dpLrWedgeAdj' },
    { label: 'dpPSSetting', value: 'dpPSSetting' },
    { label: 'dpQtape', value: 'dpQtape' },
    { label: 'dpRBarSetting', value: 'dpRBarSetting' },
    { label: 'dpRFTruckarmP1Dz', value: 'dpRFTruckarmP1Dz' },
    { label: 'dpRRDamperPerchOffsetm', value: 'dpRRDamperPerchOffsetm' },
    { label: 'dpRrPerchOffsetm', value: 'dpRrPerchOffsetm' },
    { label: 'dpRrWedgeAdj', value: 'dpRrWedgeAdj' },
    { label: 'dpRWingAngle', value: 'dpRWingAngle' },
    { label: 'dpRWingIndex', value: 'dpRWingIndex' },
    { label: 'dpRWingSetting', value: 'dpRWingSetting' },
    { label: 'dpTruckarmP1Dz', value: 'dpTruckarmP1Dz' },
    { label: 'dpWedgeAdj', value: 'dpWedgeAdj' },
    { label: 'LFbrakeLinePress', value: 'LFbrakeLinePress' },
    { label: 'LFcoldPressure', value: 'LFcoldPressure' },
    { label: 'LFpressure', value: 'LFpressure' },
    { label: 'LFrideHeight', value: 'LFrideHeight' },
    { label: 'LFshockDefl', value: 'LFshockDefl' },
    { label: 'LFshockVel', value: 'LFshockVel' },
    { label: 'LFspeed', value: 'LFspeed' },
    { label: 'LFtempCL', value: 'LFtempCL' },
    { label: 'LFtempCM', value: 'LFtempCM' },
    { label: 'LFtempCR', value: 'LFtempCR' },
    { label: 'LFtempL', value: 'LFtempL' },
    { label: 'LFtempM', value: 'LFtempM' },
    { label: 'LFtempR', value: 'LFtempR' },
    { label: 'LFwearL', value: 'LFwearL' },
    { label: 'LFwearM', value: 'LFwearM' },
    { label: 'LFwearR', value: 'LFwearR' },
    { label: 'LRbrakeLinePress', value: 'LRbrakeLinePress' },
    { label: 'LRcoldPressure', value: 'LRcoldPressure' },
    { label: 'LRpressure', value: 'LRpressure' },
    { label: 'LRrideHeight', value: 'LRrideHeight' },
    { label: 'LRshockDefl', value: 'LRshockDefl' },
    { label: 'LRshockVel', value: 'LRshockVel' },
    { label: 'LRspeed', value: 'LRspeed' },
    { label: 'LRtempCL', value: 'LRtempCL' },
    { label: 'LRtempCM', value: 'LRtempCM' },
    { label: 'LRtempCR', value: 'LRtempCR' },
    { label: 'LRtempL', value: 'LRtempL' },
    { label: 'LRtempM', value: 'LRtempM' },
    { label: 'LRtempR', value: 'LRtempR' },
    { label: 'LRwearL', value: 'LRwearL' },
    { label: 'LRwearM', value: 'LRwearM' },
    { label: 'LRwearR', value: 'LRwearR' },
    { label: 'RFbrakeLinePress', value: 'RFbrakeLinePress' },
    { label: 'RFcoldPressure', value: 'RFcoldPressure' },
    { label: 'RFpressure', value: 'RFpressure' },
    { label: 'RFrideHeight', value: 'RFrideHeight' },
    { label: 'RFshockDefl', value: 'RFshockDefl' },
    { label: 'RFshockVel', value: 'RFshockVel' },
    { label: 'RFspeed', value: 'RFspeed' },
    { label: 'RFtempCL', value: 'RFtempCL' },
    { label: 'RFtempCM', value: 'RFtempCM' },
    { label: 'RFtempCR', value: 'RFtempCR' },
    { label: 'RFtempL', value: 'RFtempL' },
    { label: 'RFtempM', value: 'RFtempM' },
    { label: 'RFtempR', value: 'RFtempR' },
    { label: 'RFwearL', value: 'RFwearL' },
    { label: 'RFwearM', value: 'RFwearM' },
    { label: 'RFwearR', value: 'RFwearR' },
    { label: 'RRbrakeLinePress', value: 'RRbrakeLinePress' },
    { label: 'RRcoldPressure', value: 'RRcoldPressure' },
    { label: 'RRpressure', value: 'RRpressure' },
    { label: 'RRrideHeight', value: 'RRrideHeight' },
    { label: 'RRshockDefl', value: 'RRshockDefl' },
    { label: 'RRshockVel', value: 'RRshockVel' },
    { label: 'RRspeed', value: 'RRspeed' },
    { label: 'RRtempCL', value: 'RRtempCL' },
    { label: 'RRtempCM', value: 'RRtempCM' },
    { label: 'RRtempCR', value: 'RRtempCR' },
    { label: 'RRtempL', value: 'RRtempL' },
    { label: 'RRtempM', value: 'RRtempM' },
    { label: 'RRtempR', value: 'RRtempR' },
    { label: 'RRwearL', value: 'RRwearL' },
    { label: 'RRwearM', value: 'RRwearM' },
    { label: 'RRwearR', value: 'RRwearR' },
];