export const outGaugeOptions = [
  { label: 'Car', value: 'Car' },
  { label: 'Flags', value: 'Flags' },
  { label: 'Gear', value: 'Gear' },
  { label: 'PlayerId', value: 'PlayerId' },
  { label: 'Speed', value: 'Speed' },
  { label: 'RPM', value: 'RPM' },
  { label: 'TurboPressure', value: 'TurboPressure' },
  { label: 'EngTemp', value: 'EngTemp' },
  { label: 'Fuel', value: 'Fuel' },
  { label: 'OilPressure', value: 'OilPressure' },
  { label: 'OilTemp', value: 'OilTemp' },
  { label: 'DashLights', value: 'DashLights' },
  { label: 'ShowLights', value: 'ShowLights' },
  { label: 'Throttle', value: 'Throttle' },
  { label: 'Brake', value: 'Brake' },
  { label: 'Clutch', value: 'Clutch' },
  { label: 'Display1', value: 'Display1' },
  { label: 'Display2', value: 'Display2' },
  { label: 'Id', value: 'Id' },
  // DashLights
  { label: 'DL_SHIFT', value: 'DL_SHIFT' },
  { label: 'DL_FULLBEAM', value: 'DL_FULLBEAM' },
  { label: 'DL_HANDBRAKE', value: 'DL_HANDBRAKE' },
  { label: 'DL_PITSPEED', value: 'DL_PITSPEED' },
  { label: 'DL_TC', value: 'DL_TC' },
  { label: 'DL_SIGNAL_L', value: 'DL_SIGNAL_L' },
  { label: 'DL_SIGNAL_R', value: 'DL_SIGNAL_R' },
  { label: 'DL_SIGNAL_ANY', value: 'DL_SIGNAL_ANY' },
  { label: 'DL_OILWARN', value: 'DL_OILWARN' },
  { label: 'DL_BATTERY', value: 'DL_BATTERY' },
  { label: 'DL_ABS', value: 'DL_ABS' },
  { label: 'DL_SPARE', value: 'DL_SPARE' },
];
